sudo: false # Run on the new AWS/Docker-based Travis CI infrastructure
language: go
go:
  - 1.4

before_install:
  # - go get -v # should not be necessary because of godep, but Travis complains of a missing package otherwise ...
