sudo: false # Run on the new AWS/Docker-based Travis CI infrastructure
language: go
go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/kr/godep

matrix:
  allow_failures:
    - go: tip
